# JavaMailSender 邮件发送的配置
spring:
  mail:
    host: smtp.qq.com
    username: ioscovers@qq.com
    #QQ邮箱的授权码
    password: hpoqvxdzmgdhbaih
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
    default-encoding: UTF-8

task:
  cron:
    tradeData: '*/5 * * * * ?'
    weather: '00 48 20 * * ?'
server:
  port: 8080